import { useColorModeValue, Flex, Text } from '@chakra-ui/react';
import Head from 'next/head';
import Container from '../components/Container';
import Hero from '../components/Hero';
import Layout from '../components/Layout';

export default function Home() {
  const bg = useColorModeValue('#ffffff', '#1C1C1C');
  return (
    <Flex
      h="100vh"
      w="100vw"
      bg={bg}
      border=" 1px solid yellow"
      justifyContent="center"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Container>
          <Flex h="50%" w="100%" border="1px solid red"></Flex>
          <Flex h="50%" w="100%" border="1px solid red"></Flex>
        </Container>
      </Layout>
    </Flex>
  );
}
